### ISSUE TITLE
Application crashed when I tried to delete a song

### ISSUE THREAD

**Issue by crysports** [hvdwolf/aosp-music#8]
I just installed this application and tried to delete a song but the application crashed.
Here is a video recording of the bug:
https://youtu.be/hhcwNJfbJYA

**Comment by maaudrana** [comment]
Lol before  creating  an issue you should  check first if this is duplicate  or not.

**Comment by crysports** [comment]
@maaudrana
That's why I closed it.
I need your help. Can you teach me how to generate a logcat?
